name: Publish package to NPM

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout to target branch
      - uses: actions/checkout@v4
        with:
          # Pull submodules
          submodules: 'recursive'

      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1

      # Setup node environment
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # Prepare, build and publish project
      - name: Install dependencies
        run: yarn

      - name: Build output files
        run: yarn build

      - name: Publish the package with a NEXT tag
        run: yarn publish --access=public --tag=next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Add LATEST tag for the published package if this is not a prerelease version
        if: github.event.release.prerelease != true
        run: npm dist-tag add ${{ steps.package.outputs.name }}@${{ steps.package.outputs.version }} latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  notify:
    needs: publish
    runs-on: ubuntu-latest
    steps:
        # Checkout to target branch
        - uses: actions/checkout@v4
  
        - name: Get package info
          id: package
          uses: codex-team/action-nodejs-package-info@v1

        - name: Set link to the github repository
          if: ${{ github.event_name != 'release ' }}
          run: |
            echo "GITHUB_LINK=${{ github.server_url }}/${{ github.repository }}" >> $GITHUB_ENV
          shell: bash
        
        # If package is released, set the link to the released version
        - name: Set github link to latest version
          if: ${{ github.event_name == 'release' }}
          run: |
            echo "GITHUB_LINK=${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}" >> $GITHUB_ENV
  
        - name: Send a message
          uses: codex-team/action-codexbot-notify@v1
          with:
            webhook: https://notify.bot.codex.so/u/IJBC1JPEBK5P
            message: '📦 [${{ steps.package.outputs.name }} ${{ steps.package.outputs.version }}](${{ env.GITHUB_LINK }}) was published'
            parse_mode: 'markdown'
            disable_web_page_preview: true